package LudoAprende_;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 * @author Leidy Milena Molano Diaz
 * Herramienta Interactiva Digital "LudoAprende"
 */

public class Tematicas extends javax.swing.JFrame {

    /**
     * Creates new form Tematicas
     */
    public Tematicas() {
        setSize(888,551);//Tamaño reajustable de la ventana
        this.setLocationRelativeTo(null);
        setTitle("LudoAprende");
        Image icon=new ImageIcon(getClass().getResource("/imagenes/Logo.png")).getImage();
        setIconImage(icon);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelTematicas = new javax.swing.JPanel();
        Instruccion = new javax.swing.JLabel();
        Video = new javax.swing.JLabel();
        BotonFamilia = new javax.swing.JButton();
        BotonFamilia1 = new javax.swing.JButton();
        BotonRopa = new javax.swing.JButton();
        BotonAnimales1 = new javax.swing.JButton();
        BotonAnimales2 = new javax.swing.JButton();
        BotonRopa1 = new javax.swing.JButton();
        BotonSalida = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelTematicas.setBackground(new java.awt.Color(95, 216, 232));
        PanelTematicas.setToolTipText("");
        PanelTematicas.setPreferredSize(new java.awt.Dimension(888, 551));

        Instruccion.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        Instruccion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Instruccion.setText("Selecciona la temática que quieras a repasar");

        Video.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Videos/Video1.gif"))); // NOI18N

        BotonFamilia.setBackground(new java.awt.Color(19, 130, 232));
        BotonFamilia.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        BotonFamilia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1. familia.png"))); // NOI18N
        BotonFamilia.setText("Familia");
        BotonFamilia.setContentAreaFilled(false);
        BotonFamilia.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotonFamilia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonFamiliaActionPerformed(evt);
            }
        });

        BotonFamilia1.setBackground(new java.awt.Color(19, 130, 232));
        BotonFamilia1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        BotonFamilia1.setText("Familia");
        BotonFamilia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonFamilia1ActionPerformed(evt);
            }
        });

        BotonRopa.setBackground(new java.awt.Color(19, 130, 232));
        BotonRopa.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        BotonRopa.setText("Prendas de Vestir");
        BotonRopa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRopaActionPerformed(evt);
            }
        });

        BotonAnimales1.setBackground(new java.awt.Color(19, 130, 232));
        BotonAnimales1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        BotonAnimales1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1. animales.png"))); // NOI18N
        BotonAnimales1.setContentAreaFilled(false);
        BotonAnimales1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAnimales1ActionPerformed(evt);
            }
        });

        BotonAnimales2.setBackground(new java.awt.Color(19, 130, 232));
        BotonAnimales2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        BotonAnimales2.setText("Animales");
        BotonAnimales2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAnimales2ActionPerformed(evt);
            }
        });

        BotonRopa1.setBackground(new java.awt.Color(19, 130, 232));
        BotonRopa1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        BotonRopa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1.Prendas.png"))); // NOI18N
        BotonRopa1.setContentAreaFilled(false);
        BotonRopa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRopa1ActionPerformed(evt);
            }
        });

        BotonSalida.setBackground(new java.awt.Color(19, 130, 232));
        BotonSalida.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        BotonSalida.setText("Salir");
        BotonSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalidaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelTematicasLayout = new javax.swing.GroupLayout(PanelTematicas);
        PanelTematicas.setLayout(PanelTematicasLayout);
        PanelTematicasLayout.setHorizontalGroup(
            PanelTematicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTematicasLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(PanelTematicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BotonFamilia, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonFamilia1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(109, 109, 109)
                .addGroup(PanelTematicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BotonAnimales1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonAnimales2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(PanelTematicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelTematicasLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(BotonRopa1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelTematicasLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(BotonRopa, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelTematicasLayout.createSequentialGroup()
                .addGroup(PanelTematicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelTematicasLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(BotonSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelTematicasLayout.createSequentialGroup()
                        .addContainerGap(75, Short.MAX_VALUE)
                        .addComponent(Instruccion, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Video)
                .addGap(128, 128, 128))
        );
        PanelTematicasLayout.setVerticalGroup(
            PanelTematicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTematicasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelTematicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelTematicasLayout.createSequentialGroup()
                        .addComponent(BotonSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Instruccion, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Video, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addGroup(PanelTematicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelTematicasLayout.createSequentialGroup()
                        .addGroup(PanelTematicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BotonFamilia, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonAnimales1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelTematicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BotonFamilia1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonAnimales2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(113, 113, 113))
                    .addGroup(PanelTematicasLayout.createSequentialGroup()
                        .addComponent(BotonRopa1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotonRopa, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(115, 115, 115))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelTematicas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelTematicas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonFamiliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonFamiliaActionPerformed
        ActFamilia familia = new ActFamilia();
        familia.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonFamiliaActionPerformed

    private void BotonFamilia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonFamilia1ActionPerformed
        ActFamilia familia = new ActFamilia();
        familia.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonFamilia1ActionPerformed

    private void BotonRopaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRopaActionPerformed
        ActRopa ropa = new ActRopa();
        ropa.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonRopaActionPerformed

    private void BotonAnimales1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAnimales1ActionPerformed
        ActAnimales animales = new ActAnimales();
        animales.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonAnimales1ActionPerformed

    private void BotonAnimales2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAnimales2ActionPerformed
        ActAnimales animalesjuego = new ActAnimales();
        animalesjuego.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonAnimales2ActionPerformed

    private void BotonRopa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRopa1ActionPerformed
        ActRopa ropa = new ActRopa();
        ropa.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonRopa1ActionPerformed

    private void BotonSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalidaActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BotonSalidaActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAnimales1;
    private javax.swing.JButton BotonAnimales2;
    private javax.swing.JButton BotonFamilia;
    private javax.swing.JButton BotonFamilia1;
    private javax.swing.JButton BotonRopa;
    private javax.swing.JButton BotonRopa1;
    private javax.swing.JButton BotonSalida;
    private javax.swing.JLabel Instruccion;
    private javax.swing.JPanel PanelTematicas;
    private javax.swing.JLabel Video;
    // End of variables declaration//GEN-END:variables
}
